### PR TITLE
Improvement/hkw 1297

### PR DESCRIPTION
**Pull request by tnguyen440**

### CODE REVIEW

**Comment by digisz** [comment]
Let me add some rational to this PR

We discovered through User Testing and Feedback, that the link colors have some issues

- hard to tell the difference between text and link
- not able to tell if link has been visited before

After some investigation we saw, that the contrasts do not fit the WCGA 2.0 AA standards and need to be improved. 

Therefore we propose the following changes:

Change body color to be 1A1A1A (higher contrast)
Change a:normal to be 494df4 (Indigo)
Change a:hover to be 00005b (Deep Sapphire) + Underline
Change a:visited to be BC30C1
Change a:active to be 00005b (Deep Sapphire)

**Comment by FKSI** [comment]
@digisz Thanks! I was having a hard-time to find-out the origin of the PR. 
@tnguyen440 `v2` branch is most up-to-date branch, can you switch the PR?

**Comment by tnguyen440** [comment]
@digisz thanks for explaining the reason why we have this PR
@FKSI I will. Currently we are using v1 for axahongkong so that why I made this PR to v1

**Review by FKSI — APPROVED** [review]

**Comment by FKSI** [comment]
@tnguyen440 I don't think that there will be any blockers for merging into `v2`. Feel free to do it whenever you are ready :). Thanks guys for the contribution 🇭🇰

**Pull request merged**
