### PR TITLE
Add a color page

### PR DESCRIPTION
**Pull request by elessar-ch**
This adds a color page that looks something like this:
image

### CODE REVIEW

**Comment by FKSI** [comment]
Can we make the copy button same as in the component pages?
capture d ecran 2016-11-17 a 19 44 09

**Comment by elessar-ch** [comment]
I think we should probably write to each color what you should use it for.
Like: Indigo Blue: "Use for links in text or backgrounds."

**Comment by elessar-ch** [comment]
@FKSI I feel like copy pasting the exact values is a more important use case on this page than on the code-snippets where you might select only part of a snippet.

**Comment by FKSI** [comment]
@elessar-ch Sorry, I wasn't really clear. What I mean, is the button should have `copy` written inside instead of having an icon. 

> I think we should probably write to each color what you should use it for.
> Like: Indigo Blue: "Use for links in text or backgrounds."

How about linking to the Web Guidelines?

**Comment by elessar-ch** [comment]
@davidknezic wanna post a screenshot of your suggestion?

**Comment by davidknezic** [comment]
Will do in the train

**Comment by davidknezic** [comment]
Here's the design suggestion:
https://design.axa.com/feature-color-page/api/colors.html

It's aim is to make the colors more visible, while keeping the design subtle.

What do you think @elessar-ch @FKSI?

**Comment by davidknezic** [comment]
Added descriptions to some of the colors. We can reach out to Adrien or Patrick for the others, but this can be done in another pr IMO.

**Comment by elessar-ch** [comment]
I think we can merge this, no?

**Review by FKSI — APPROVED** [review]

**Pull request merged**
