### PR TITLE
Introduce form components

### PR DESCRIPTION
**Pull request by sventschui**
@TheDadi as discussed
@davidknezic 4yi

https://design.axa.com/toolkit/forms/components/form-and-input-elements/form.html

TODO:
- [x] textfield: Autocomplete SEE #135 
- [x] select: Create another PR for a fully styled dropdown SEE #134 
    - Color change of the dropdown icon not possible using css only
    - Styling options not possible using css only
- [x] select / radio / checkbox: Discuss about sticky hover effect of radio buttons, checkboxes and selects (see wtfforms.com)
- [x] radio: Get the missing specs for Radio1 on desktop
- [x] radio: Use `typo-15` instead of `typo-16` in `.custom-radio.radio1`
- [x] radio / checkbox: review disabled state (no design spec) SEE #137
- [x] error: error icon to the left of the form fields
- [x] Proper docs
- [x] Add form components to docs navigation
- [x] file upload: File upload SEE #136
- [x] Cross Browser testing
- [x] Proper in-form tooltips (currently default bootstrap tooltip is used) SEE #138 
- [x] Use publico font as form heading

### CODE REVIEW

**Comment by FKSI** [comment]
Guys keep in mind that 2 PR (for both `v1 branch` and `v2 branch`)  are coming with the Brand Refresh.

The expected changelog:

- New colors (⚠️ no refactoring, only values have been changed)
- New icons

**Comment by sventschui** [comment]
@FKSI doesn't seem to have a big impact, hopefully

**Comment by FKSI** [comment]
@sventschui Technically it shouldn't be, but is more graphically speaking. Colors association could go totally wrong with the new palette ;).

**Comment by sventschui** [comment]
Just ran a rough test on browserstack using:
- Nexus 7, Android 4.4, Chrome
- Windows 10, Edge 15
- OS X, Mavericks, Safari 7.1
- OS X, Yosemite, Safari 8
- OS X, Sierra, Safari 10
- iPhone 5S, Safari 7 *(flex-box is broken)*
- iPhone 6, Safari 8 *(flex-box is broken)*
- iPhone 6S, Safari 9
- iPhone 6S, Firefox
- iPhone 6S, Chrome
- Lumia 930, WP 8.1 (Simulator)

flex-box seems to be broken sometimes on iOS <= 8, otherwise everything is ok

**Comment by sventschui** [comment]
@davidknezic @elessar-ch @TheDadi @FKSI shall we merge the current work and work on the open points in diffrent PRs once needed?

Before merging we will need to revert the Jenkinsfile :)

**Comment by sventschui** [comment]
Current work is deployed here: https://design.axa.com/toolkit/forms/components/form-and-input-elements/form.html

**Comment by davidknezic** [comment]
Great work @sventschui!

Do you have an idea why our build fails with...?

>sh: 1: webpack: not found

**Comment by sventschui** [comment]
Docker build works on my machine. Can you please flush the docker image cache on jenkins?

**Review by davidknezic — APPROVED** [review]
Fantastic!

**Pull request merged**
