### PR TITLE
rework styles using bs4

### PR DESCRIPTION
**Pull request by TheDadi**
Too lazy to write descriptive message

edit @davidknezic: see https://design.axa.com/feature-bootstrap-v4

#95

### CODE REVIEW

**Comment by davidknezic** [comment]
Beautiful @TheDadi! Will review!

**Comment by TheDadi** [comment]
bootstrap examples are still broken

**Comment by davidknezic** [comment]
This branch is autodeployed here:
https://design.axa.com/feature-bootstrap-v4

**Comment by sventschui** [comment]
Header search is broken on desktop since glyphicons are not included. Move to inline SVG?!

**Comment by TheDadi** [comment]
there are no glyphicons anymore in bs4 maybe switch to fontawesome

**Comment by sventschui** [comment]
@TheDadi I know. That's why I'd recommend to move to inline SVGs

**Comment by davidknezic** [comment]
Yes, inline SVG sounds good!

**Comment by davidknezic** [comment]
I'm gonna continue working on this pr, I'd like to release this as `v2.0.0-alpha.1`.

This means we'll have the following branches:

* `master` or `v1` which will currently point to `v1.0.0-alpha.8`.
* `v2` where I'm going to merge this pr as `v2.0.0-alpha.1`.

You all ok with that? @TheDadi @sventschui @FKSI @elessar-ch?

**Comment by sventschui** [comment]
okay with that :)

**Review by davidknezic — APPROVED** [review]
Thanks a lot @TheDadi!

Merging this now, it's going to be hosten on https://design.axa.com/toolkit-v2/

Things we should have a look at in separate pr's:

* clean up our _variables.scss
* revive the bootstrap docs page

**Pull request merged**
