### PR TITLE
Make docs-example-devices-list more fancy

### PR DESCRIPTION
**Pull request by sventschui**
screen shot 2016-11-08 at 19 41 15

Thanks to @davidknezic for the inspiration :)

### CODE REVIEW

**Comment by davidknezic** [comment]
It looks great @sventschui, much more decent and doesn't add a big empty margin to the top anymore.

**Comment by davidknezic** [comment]
Oh yeah!

We have some custom transition variables in `_variables.scss`.

``` scss
$transition-default: cubic-bezier(0.4, 0.0, 0.2, 1);
$transition-easeout: cubic-bezier(0.0, 0.0, 0.2, 1);
$transition-easein: cubic-bezier(0.4, 0.0, 1, 1);
$transition-ease: cubic-bezier(0.4, 0.0, 0.6, 1);

$transition-fast: 195ms;
$transition-slow: 375ms;
$transition-normal: 225ms;

$transition-delay-fast: $transition-fast;
$transition-delay-slow: $transition-slow;
$transition-delay-normal: $transition-normal;
```

Wondering where we could document those, so they're easy to find when adding transitions to components?

**Comment by sventschui** [comment]
Using the variables now.

Would suggest a "Build your own components" page/section

**Review by davidknezic — APPROVED** [review]
Very cool!

**Pull request merged**
